[app]
name = "Your Application"
mode = "development"
version = 1


# Driver Configuration

[apis]
port = 3999

[apis.cors]
allowed_origins = ["*"]
allowed_methods = ["*"]

[monitoring]
otel_endpoint = "localhost:4317"
enable_collect_log = false
enable_telemetry = false


[default_database]
adapter = "postgres-sql/db"
encoding = "UTF-8"
host = "localhost"
reconnect = false
sslmode = false             # postgres only
alias = "default"
pool = 10
port = 5431
database_name = "goceng"
schema = "public"
username = "postgres"
password = "admin"


[[databases_sql]]
adapter = "postgres-gorm"
encoding = "UTF-8"
alias = "gorm"
reconnect = false
host = "localhost"
pool = 10
port = 5431
schema = "public"
database_name = "goceng"
username = "postgres"
password = "admin"


# [[databases_sql]]
# adapter = "mysql"
# encoding = "UTF-8"
# alias = "cluster_2"
# reconnect = false
# host = "localhost"
# pool = 10
# port = 5432
# database_name = "test"
# username = "tiul"
# password = "password"

# [smtp]
# host = ""
# port = 0
# username = ""
# password = ""

# # SMTP AUTH - PLAIN (default) or LOGIN
# auth_method = ""

# # Whether to enforce TLS encryption for the mail server connection.
# #
# # When set to false StartTLS command is send, leaving the server
# # to decide whether to upgrade the connection or not.
# tls = false

# # LocalName is optional domain name or IP address used for the
# # EHLO/HELO exchange (if not explicitly set, defaults to "localhost").
# #
# # This is required only by some SMTP servers, such as Gmail SMTP-relay.
# local_name = ""
